Fix possible heap corruption when converting to NSNonLossyASCIIStringEncoding
gnustep/libs-base pull request #189
Opened 2021-07-02 15:52 UTC by triplef

Possible heap corruption because `sprintf()` always appends NULL terminator, which is written past the end of the `ptr` buffer for the last character in the string.

Was exposed by existing `NSString/basic` test when checking for "latin1 in lossy encoding", as the last character of that string is running into the affected code. When running tests using the Windows MSVC toolchain this was showing a "HEAP CORRUPTION DETECTED" error.

2021-07-02 17:17 UTC, rfm requested changes
As I understand it, the problem is that if we need an ocat or hex escape sequence for the last character in the string, the nul terminator of the sprintf will overrun the buffer.

Unless I miss something about snprintf, replacing each call to sprintf with one to snprintf should fix that (no need to inefficiently write into a separate buffer and then copy back).

But with efficiency in mind, we could go better than that and generate the octal or hex sequence directly.
eg
ptr[dpos + 3] = "01234567"[u / 8];
u /= 8;
ptr[dpos + 2] = "01234567"[u / 8];
...

Of course that's a lot more lines of code and a chance to make mistakes, so perhaps just replacing sprintf with snprintf is best?

What do you think?

2021-07-02 17:30 UTC, rfm commented
Given that I managed to make an error (u / 8 when I meant u % 8) in that snippet of code, snprintf seems the safer option.

2021-07-02 18:33 UTC, triplef commented
If I read the man page correctly snprintf() always adds a nul terminator, so I don't think there's a way to use either sprintf() or snprintf() without a separate buffer.

It does seem not so great performance wise though. I'll see if I can come up with a concise way to build these strings manually.

2021-07-02 19:11 UTC, triplef commented
How is this?

2021-07-03 05:41 UTC, rfm approved these changes
That looks fne.
You are right about snprintf (its behavior just seems really unintuitive to me): I actually had to write a test program to convince myself about that reading of the documentation!

2021-07-03 06:34 UTC, merged

2021-07-03 06:34 UTC, triplef commented
Yeah same, had to write a test program too...