NSNetService and NSNetServiceBrowser: Throw runtime exceptions
gnustep/libs-base pull request #384
Opened 2024-03-30 14:12 UTC by qmfrederik

Always compile `NSNetService` and `NSNetServiceBrowser`, but have their `intialize` method throw an exception if libavahi and mDNS are unavailable.

This:
- Results in a clear error message if code which was compiled agains a copy of GNUstep with avahi/mDNS support runs on a copy of GNUstep which doesn't have avahi/mDNS support.
- Avoids code which uses `NSNetService` or `NSNetServiceBrowser` to successfully compile (because the classes are defined in the header) but then failing to link (because there is no implementation for these classes).

2024-03-30 14:29 UTC, qmfrederik commented
The test failures are unrelated, should be fixed via #383

2024-03-30 16:33 UTC, gcasa commented
@rfm, @qmfrederik I agree with the building of NSNetServices no matter what, that makes perfect sense, the part I am uncertain about is throwing an exception.  This may cause code that might otherwise function to fail unless modified to catch the exception.   @rfm, please use your discretion to decide what you believe should happen here.

2024-03-30 17:01 UTC, gcasa commented
@rfm, @qmfrederik another option here may be to introduce a default/setting that will allow setting this behavior.   It could be off (e.g. simply log) by default, but throw an exception if needed and could be set in an application's defaults.

2024-03-31 10:55 UTC, rfm requested changes
I think Greg likes the idea of everything looking fine (it being able to build/link Apple code with gnustep as easily as possible), even if the code than silently fails to work when used ... the blame is attached to the developer who failed to check the return value from the method to get an instance of a class (which returned nil).

I do not agree with that approach, preferring the opposite: I think code that can't work should fail at compile time so that the developer knows about it and can fix it.  If I was going to improve on the existing code I'd perhaps want to make it clearer to the developer, at the point when they try to compile, exactly *why* the feature is not available and how to fix it.

This patch seems to move to somewhere between these two approaches, with the advantages of neither, so I'm not sure what the motivation is.  Can you explain?

2024-03-31 12:01 UTC, qmfrederik commented
So there's two dimensions to this:

### Handing an initialization failure

[The Apple documentation](https://developer.apple.com/library/archive/documentation/General/Conceptual/CocoaEncyclopedia/Initialization/Initialization.html#//apple_ref/doc/uid/TP40010810-CH6-SW57) states, in the "Issues with Initializers" section:

> Sometimes an `init...` method cannot perform the initialization requested. For example, an `initFromFile:` method expects to initialize an object from the contents of a file, the path to which is passed as a parameter. But if no file exists at that location, the object cannot be initialized. A similar problem happens if an `initWithArray:` initializer is passed an `NSDictionary` object. When an `init...` method cannot initialize an object, it should:
> - Release the newly allocated object (in memory-managed code)
> - Return `nil`
>
> Returning nil from an initializer indicates that the requested object cannot be created.

The [`init documentation`](https://developer.apple.com/documentation/objectivec/nsobject/1418641-init) documentation makes a similar statement:

> If the new object can’t be initialized, the method should return `nil`.

So in that view, I think @gcasa is right, and "blame is attached to the developer who failed to check the return value from the method to get an instance of a class (which returned nil)."

In that spirit, I've updated the PR to have `[NSNetService initWithDomain]` and `[NSNetServiceBrowser init]` return `nil`.

### Compile time versus runtime

libavahi/mDNS are optional dependencies of GNUstep, so it's possible to compile GNUstep without a working implementation of `NSNetService` and `NSNetServiceBrowser`.

In the current situation, you get a linker error when you compile code that uses `NSNetService(Browser)` because the classes are defined in the headers but don't exist in gnustep-base.  You would get a runtime exception when you run code which has been built using a copy of GNUstep which has avahi/mDNS support using a copy of GNUstep which doens't have that optional dependency.

It's the second scenario I'm most concerned with -- `NSNetService(Browser)` is part of the GNUstep API.  So I believe GNUstep should always include an implementation of these interfaces.  The conventional way to signal that a class is non-functional is by having its `init` method return `nil`, which the proposed change does.

2024-03-31 15:10 UTC, qmfrederik commented
The other option (perhaps in combination with the patch as currently proposed) is to not install the headers for `NSNetService` and `NSNetServiceBrowser` if the classes are not implemented.

However, if we go down that path, what would Objective-C code which accounts for both scenarios (with and without bonjour support) look like?  If you have the runtime check, you could do `if ([[NSNetService] alloc] init] == nil)`, but what would you do if the headers are missing?

2024-04-02 09:28 UTC, rfm approved these changes
OK.  I would ideally like a compile time warning, but I don't see a good way to do that.  So I think this is good to commit.

2024-04-02 18:34 UTC, gcasa commented
> I think Greg likes the idea of everything looking fine (it being able to build/link Apple code with gnustep as easily as possible), even if the code than silently fails to work when used ... the blame is attached to the developer who failed to check the return value from the method to get an instance of a class (which returned nil).
> 
> 
> 
> I do not agree with that approach, preferring the opposite: I think code that can't work should fail at compile time so that the developer knows about it and can fix it.  If I was going to improve on the existing code I'd perhaps want to make it clearer to the developer, at the point when they try to compile, exactly *why* the feature is not available and how to fix it.
> 
> 
> 
> This patch seems to move to somewhere between these two approaches, with the advantages of neither, so I'm not sure what the motivation is.  Can you explain?

I try to take things on a more case by case basis.

My feeling is that many users are not necessarily developers.  Throwing a runtime exception might cause a crash in an application that is not using NSNetService for any core functionality.  For instance, Eggplant uses it, but can launch and function without it and the application remains fully usable.

So here it was my feeling that, in some cases, there may be applications that will use NSNetService in a similar way so introducing an exception would be a disruptive change in behavior.

That being said, I agree with @rfm 's decision.

2024-04-03 19:06 UTC, qmfrederik commented
Thanks both.  I'm not a contributor to this repo, so I'd rely on someone else to go ahead and merge this.

2024-04-04 03:48 UTC, gcasa commented
> Thanks both.  I'm not a contributor to this repo, so I'd rely on someone else to go ahead and merge this.

Given @rfm 's approval I will proceed to merge.  Thanks @qmfrederik

2024-04-04 03:49 UTC, merged