Implement -[NSFileManager URLsForDirectory:inDomains:]
gnustep/libs-base pull request #419
Opened 2024-06-10 18:47 UTC by 2xsaiko

This behaves like NSSearchPathForDirectoriesInDomains (at least, superficially. Not sure if Apple's implementation has some special behavior on top that their documentation doesn't mention.)

The documentation comment is copied from NSSearchPathForDirectoriesInDomains.

2024-06-11 09:15 UTC, rfm requested changes
The concept is fine, but there are two show-stopping issues of non-portable coding with the implementation:

1. The use of generics:  you need to replace the generic syntax with the macros provided in NSObjCRuntime.h
2. The use of blocks:  you need to replace any blocks code with portable code.  In this case it's simple enumeration so you might best use the FOR_IN macro provided in GSFastEnumeration.h

2024-06-11 09:26 UTC, gcasa commented
@2xsaiko I don't believe a copyright assignment is needed for this change.  Please write assign@gnu.org and request a copyright assignment for GNUstep and CC me on the request.   Also, please make the changes suggested via @rfm.  The reason is that GNUstep supports more compilers than just clang and not all support the same features.  Thank you, GC

2024-06-11 09:28 UTC, gcasa commented
Sorry, I accidentally hit the "close" button.  I reopened this.

2024-06-11 15:23 UTC, 2xsaiko commented
Done!

2024-06-12 10:00 UTC, rfm approved these changes
One tiny issue; the dot syntax to access a property is non-portable; older compilers don't support properties, so we must call the method to get the count of objects in the paths array.

However, I'll merge and then fix that rather than holding things up.

2024-06-12 10:00 UTC, merged

2024-06-12 10:06 UTC, rfm commented
oops ... also an excess RELEASE to be removed and some formatting tweaks