Fix regex callback
gnustep/libs-base pull request #476
Opened 2024-12-11 23:23 UTC by sensetalkdoug

The Cocoa block uses a "stop" flag to allow a client to abort a long-running regex process. But the ICU library expects the callback function to return a flag with the opposite meaning -- "keepGoing". This change reverses the flag to fix the problem that any regex process that ran long enough to invoke the callback would be prematurely canceled.

2024-12-18 18:42 UTC, johnathan-becker commented
@rfm Can you please review this.

2024-12-18 19:05 UTC, rfm requested changes
While there's nothing actually wrong here, I think the new variable slightly detracts from the clarity of the implementation.  Simply testing the value of 'stop' seems cleaner to me:

eg.

if (stop)
  {
    return FALSE;
  }
else
  {
    return TRUE;
  }

2024-12-18 19:09 UTC, rfm requested changes
I don't think the change to GNMUmakefile.preamble is correct (or necessary) as it will cause compilation failure on systems without blocks,  and on systems with blocks the flag should be added automaticaly anyway.

On a related issue, the test itself needs to be conditionally compiled so that it doesn't run on systems without blocks or *(better) use the macros to simulate blocks if possible (see other blocks-specific testcases for an example).

2025-01-04 15:11 UTC, closed without merging

2025-01-04 15:11 UTC, rfm commented
I included parts of this in recent changes to render RE enumeration available to the classic compiler/runtime.